blank_issues_enabled: false
contact_links:
  - name: Elvis DB Access Request
    url: https://jira.harman.com/jira/servicedesk/customer/portal/84
    about: Request credentials for the Elvis Report Database
